---
title: "Further Analysis"
author: "Group 10"
link: https://www.kaggle.com/datasets/clkmuhammed/creditscoreclassification
---

```{r Data}
library(dplyr)
library(ggplot2)

# Load in final data set with tested values
FinalTestData <- read.csv("FinalTestData.csv")
```


```{r Further Data Analysis}

# Each customer in this new data set is observed 4 times, rather than 8 like the training data
test <- FinalTestData %>% group_by(Customer_ID) %>%  summarise(numObservations = n())
table(test$numObservations)


# We want to look at the final month for each customer to see if their credit is acceptable or not
FinalMonth <- seq(from = 4, to = nrow(FinalTestData), length.out = nrow(FinalTestData)/4)
#subsetting the data to only take the last month of each customer
CustFinalMonth <- FinalTestData[FinalMonth,]


# This value shows us that 71.936% of customers have an acceptable Credit Score rating
mean(CustFinalMonth$Credit_Score == "Acceptable")

# Bar plot of Credit score rating by occupation
ggplot(data = CustFinalMonth, aes(x = Occupation, color = Credit_Score)) + geom_bar() +theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))


# filtered data of all records with Acceptable Credit score rating
Acceptable <- CustFinalMonth %>% filter(Credit_Score == "Acceptable")

# filtered data of all records with Unacceptable Credit score rating
Unacceptable <- CustFinalMonth %>% filter(Credit_Score == "Unacceptable")

# Income metrics 
summary(Acceptable$Annual_Income)
summary(Unacceptable$Annual_Income)

Aincome <- hist(Acceptable$Annual_Income)
Uincome <- hist(Unacceptable$Annual_Income)

A1 <- rgb(255,0,0, max = 255, alpha = 80, names = "lt.red")
U2 <- rgb(0,0,153,max = 255, alpha = 80, names = "lt.blue")


plot(Aincome, col = A1, xlab = "Income", main = "Income by Credit Score");plot(Uincome, add = TRUE, col = U2);legend("topright", c("Acceptable", "Unacceptable"), fill=c("pink", "light blue"))


# Debt metrics and visualizations
summary(Acceptable$Outstanding_Debt)
summary(Unacceptable$Outstanding_Debt)

hA <- hist(Acceptable$Outstanding_Debt)
hU <- hist(Unacceptable$Outstanding_Debt)

A1 <- rgb(255,0,0, max = 255, alpha = 80, names = "lt.red")
U2 <- rgb(0,0,153,max = 255, alpha = 80, names = "lt.blue")


plot(hA, col = A1, xlab = "Outstanding Debt", main = "Credit Score Outstanding Debt");plot(hU, add = TRUE, col = U2);legend("topright", c("Acceptable", "Unacceptable"), fill=c("pink", "light blue"))


# Interest rate visualizations
summary(Acceptable$Interest_Rate)
summary(Unacceptable$Interest_Rate)

(Acceptable$Interest_Rate)

ggplot(data = CustFinalMonth, aes(x = Interest_Rate, color = Credit_Score)) + geom_histogram()

```

