---
title: "BZAN 542 Project"
author: "Group 10"
link: https://www.kaggle.com/datasets/clkmuhammed/creditscoreclassification
---

```{r Load in data and packages}
library(regclass)  
library(rpart)
library(randomForest)
library(gbm)
library(caret)
library(pROC)
library(dplyr)
library(tidyr)
library(ggplot2)

# library(h2o) #automl https://github.com/h2oai/h2o-tutorials/tree/master/h2o-world-2017/automl
# #h2o.automl()


#Training and Holdout data are already defined on Kaggle
# Create training and backup to training data
Train_Backup <- read.csv("train.csv")
DATA <- Train_Backup

# Loading in testing data and creating a backup
Test_Backup <- read.csv("test.csv")
TEST <- Test_Backup

# Splitting Data into Training and Holdout sets
set.seed(542) # set the seed so it is the same TRAIN and HOLDOUT for whoever runs the code
train.rows <- sample(1:nrow(DATA), .7*nrow(DATA))

TRAIN <- DATA[train.rows,]
HOLDOUT <-  DATA[-train.rows,]

```



**Data Exploration**

```{r Data Exploration}
# Data is broken down by customer.
DATA[which(DATA$Customer_ID == 3392),]
# Each customer looks to have 8 months worth of credit data
test <- DATA %>% group_by(Customer_ID) %>%  summarise(numObservations = n())
table(test$numObservations)
# Customers observations will be separated in TRAINING and HOLDOUT because the records are randomly chosen

# The TRAIN dataset has an extra column (Credit_Score). This appears to be the variable that we will be predicting with the HOLDOUT data.
colnames(DATA)[which(colnames(DATA)!=colnames(TEST))]

# Checking for NAs in both datasets
Train_NA <- sapply(TRAIN, function(y) sum(length(which(is.na(y))))) 
data.frame(Train_NA) # No NAs in the TRAINING data

Holdout_NA <- sapply(HOLDOUT, function(y) sum(length(which(is.na(y))))) 
data.frame(Holdout_NA) # No NAs in the HOLDOUT data
```

Some questions to think about:

-What determines if a client qualifies for a credit card loan?

-Does payment behavior correlate with loan acceptance?

-How does bad credit affect loan acceptance?

-How does occupation affect credit scores?


**Data Cleaning**

```{r Data Cleaning}
# We received data for both training and testing. 
# The Training data was split into the HOLDOUT and TRAIN data sets seen here
# The TEST data set also needs to undergo the same cleaning process in order to be used by the model
# We want to limit the amount of columns that use text, to give the model more data to make predictions on


# Setting ID numbers to be factor data type
TRAIN$ID <- as.factor(TRAIN$ID)
TRAIN$Customer_ID <- as.factor(TRAIN$Customer_ID)

HOLDOUT$ID <- as.factor(HOLDOUT$ID)
HOLDOUT$Customer_ID <- as.factor(HOLDOUT$Customer_ID)

TEST$ID <- as.factor(TEST$ID)
TEST$Customer_ID <- as.factor(TEST$Customer_ID)


# Group Good and Standard Credit to be "Acceptable" and leave bad as "Unacceptable"
# table(TRAIN$Credit_Score)
TRAIN$Credit_Score <- as.factor(ifelse(TRAIN$Credit_Score == "Poor", "Unacceptable", "Acceptable"))
HOLDOUT$Credit_Score <- as.factor(ifelse(HOLDOUT$Credit_Score == "Poor", "Unacceptable", "Acceptable"))
# Poor credit score would be acceptable, good or standard would be unacceptable


# Change Credit_Mix ( Bad = 0, Standard = 1, Good = 2 )
TRAIN$Credit_Mix <- as.factor(ifelse(TRAIN$Credit_Mix == "Bad", 0, ifelse(TRAIN$Credit_Mix == "Standard", 1, 2)))
HOLDOUT$Credit_Mix <- as.factor(ifelse(HOLDOUT$Credit_Mix == "Bad", 0, ifelse(HOLDOUT$Credit_Mix == "Standard", 1, 2)))
TEST$Credit_Mix <- as.factor(ifelse(TEST$Credit_Mix == "Bad", 0, ifelse(TEST$Credit_Mix == "Standard", 1, 2)))



# Changing Payment_Behavior from a word to a T/F
TRAIN$High_spent_Large_value_payments <- ifelse(TRAIN$Payment_Behaviour == "High_spent_Large_value_payments", 1, 0)
TRAIN$High_spent_Medium_value_payments <- ifelse(TRAIN$Payment_Behaviour == "High_spent_Medium_value_payments", 1, 0)
TRAIN$High_spent_Small_value_payments <- ifelse(TRAIN$Payment_Behaviour == "High_spent_Small_value_payments", 1, 0)
TRAIN$Low_spent_Large_value_payments <- ifelse(TRAIN$Payment_Behaviour == "Low_spent_Large_value_payments", 1, 0)
TRAIN$Low_spent_Medium_value_payments <- ifelse(TRAIN$Payment_Behaviour == "Low_spent_Medium_value_payments", 1, 0)
TRAIN$Low_spent_Small_value_payments <- ifelse(TRAIN$Payment_Behaviour == "Low_spent_Small_value_payments", 1, 0)
TRAIN$Payment_Behaviour <- NULL

HOLDOUT$High_spent_Large_value_payments <- ifelse(HOLDOUT$Payment_Behaviour == "High_spent_Large_value_payments", 1, 0)
HOLDOUT$High_spent_Medium_value_payments <- ifelse(HOLDOUT$Payment_Behaviour == "High_spent_Medium_value_payments", 1, 0)
HOLDOUT$High_spent_Small_value_payments <- ifelse(HOLDOUT$Payment_Behaviour == "High_spent_Small_value_payments", 1, 0)
HOLDOUT$Low_spent_Large_value_payments <- ifelse(HOLDOUT$Payment_Behaviour == "Low_spent_Large_value_payments", 1, 0)
HOLDOUT$Low_spent_Medium_value_payments <- ifelse(HOLDOUT$Payment_Behaviour == "Low_spent_Medium_value_payments", 1, 0)
HOLDOUT$Low_spent_Small_value_payments <- ifelse(HOLDOUT$Payment_Behaviour == "Low_spent_Small_value_payments", 1, 0)
HOLDOUT$Payment_Behaviour <- NULL

TEST$High_spent_Large_value_payments <- ifelse(TEST$Payment_Behaviour == "High_spent_Large_value_payments", 1, 0)
TEST$High_spent_Medium_value_payments <- ifelse(TEST$Payment_Behaviour == "High_spent_Medium_value_payments", 1, 0)
TEST$High_spent_Small_value_payments <- ifelse(TEST$Payment_Behaviour == "High_spent_Small_value_payments", 1, 0)
TEST$Low_spent_Large_value_payments <- ifelse(TEST$Payment_Behaviour == "Low_spent_Large_value_payments", 1, 0)
TEST$Low_spent_Medium_value_payments <- ifelse(TEST$Payment_Behaviour == "Low_spent_Medium_value_payments", 1, 0)
TEST$Low_spent_Small_value_payments <- ifelse(TEST$Payment_Behaviour == "Low_spent_Small_value_payments", 1, 0)
TEST$Payment_Behaviour <- NULL


# Dropping columns that won't be used in the model
TRAIN$Name <- NULL
TRAIN$Month <- NULL
TRAIN$SSN <- NULL
TRAIN$Occupation <- NULL
TRAIN$Type_of_Loan <- NULL


HOLDOUT$Name <- NULL
HOLDOUT$Month <- NULL
HOLDOUT$SSN <- NULL
HOLDOUT$Occupation <- NULL
HOLDOUT$Type_of_Loan <- NULL

TEST$Name <- NULL
TEST$Month <- NULL
TEST$SSN <- NULL
TEST$Occupation <- NULL
TEST$Type_of_Loan <- NULL


# Figure out what NM is and what to do with it
#TRAIN$Payment_of_Min_Amount <- as.factor(TRAIN$Payment_of_Min_Amount)
TRAIN$Payment_of_Min_Amount <- NULL
HOLDOUT$Payment_of_Min_Amount <- NULL
TEST$Payment_of_Min_Amount <- NULL


# write.csv(TRAIN, "Cleaned_TRAIN.csv", row.names = F)
# write.csv(HOLDOUT, "Cleaned_HOLDOUT.csv", row.names = F)
# write.csv(TEST, "Cleaned_TEST.csv", row.names = F)


```


```{r Cleaned Data}

# Cleaned data
CleanTRAIN <- read.csv("Cleaned_TRAIN.csv")
CleanTRAIN$Credit_Score <- as.factor(CleanTRAIN$Credit_Score)
CleanTRAIN$Credit_Mix <- as.factor(CleanTRAIN$Credit_Mix)

CleanHOLDOUT <- read.csv("Cleaned_HOLDOUT.csv")
CleanHOLDOUT$Credit_Score <- as.factor(CleanHOLDOUT$Credit_Score)
CleanHOLDOUT$Credit_Mix <- as.factor(CleanHOLDOUT$Credit_Mix)
```



**ML Modeling**

```{r Decision Tree}
TREE <- rpart(Credit_Score~. -ID -Customer_ID,data=CleanTRAIN) # Create Decision Tree Model
visualize_model(TREE) # Visualize Decision Tree Model
```


```{r GLM}
# Tune parameters for GLM
fitControl <- trainControl(
  method = "cv",
  number = 5,
  classProbs = TRUE,
  allowParallel = TRUE,
  summaryFunction = twoClassSummary
)

# Create GLM model
GLM <-train(Credit_Score~. -ID -Customer_ID,
            data = CleanTRAIN,
            trControl= fitControl,
            preProc=c("center","scale"),
            method = "glm")

GLM$results
varImp(GLM) # variable importance of GLM
plot(varImp(GLM)) # Visualization for GLM model
```


```{r GLMNET}
# Tune parameters for GLMNET
glmnetGrid <- expand.grid(alpha = seq(0,1,.1),lambda = 10^seq(-5,-1,by=0.25))

fitControl <- trainControl(
  method = "cv",
  number = 5,
  classProbs = TRUE,
  allowParallel = TRUE,
  summaryFunction = twoClassSummary
)


# Create GLMNET model
GLMNET <- train(Credit_Score~. - ID - Customer_ID,
                data = CleanTRAIN,
                trControl=fitControl,
                preProc=c("center","scale"),
                method = "glmnet",
                tuneGrid=glmnetGrid)

GLMNET$results[rownames(GLMNET$bestTune),] # finding best results from GLMNET model
plot(GLMNET) # Visualization for RPART model
```


```{r Rpart}
# Tune parameters for RPART
rpartGrid <- expand.grid(cp=10^seq(-5,-1,by=0.2))

fitControl <- trainControl(
  method = "cv",
  number = 5,
  classProbs = TRUE,
  allowParallel = TRUE,
  summaryFunction = twoClassSummary
)


# Create RPART model
RPART <- train(Credit_Score~. -ID -Customer_ID,
               data = CleanTRAIN,
               trControl=fitControl,
               preProc=c("center","scale"),
               method = "rpart",
               tuneGrid=rpartGrid) 

RPART$results[rownames(RPART$bestTune),] # finding best results from RPART model
plot(RPART) # Visualization for RPART model
```


**Testing and Comparing Models**

```{r Results}
# Training results comparison
TRAININGresults <- rbind(
  GLM$results[c("ROC","Sens", "Spec", "ROCSD", "SensSD", "SpecSD")],
  GLMNET$results[which.max(GLMNET$results$ROC),c("ROC","Sens", "Spec", "ROCSD", "SensSD", "SpecSD")],
  RPART$results[which.max(RPART$results$ROC),c("ROC","Sens", "Spec", "ROCSD", "SensSD", "SpecSD")]
)

rownames(TRAININGresults) <- c('GLM','GLMNET','RPART')

TRAININGresults

# Visualizations for ROC, Sens (true positive), Spec (true negative)
results <- resamples(list(GLM=GLM, GLMNET=GLMNET, RPART=RPART))
scales <- list(x=list(relation="free"), y=list(relation="free"))
bwplot(results, scales=scales)


# difference in model predictions, summarize p-values for pair-wise comparisons
summary(diff(results))


# Holdout Results comparison
HOLDOUTresults <- rbind(
  postResample(predict(GLM,newdata=CleanHOLDOUT),CleanHOLDOUT$Credit_Score),
  postResample(predict(GLMNET,newdata=CleanHOLDOUT),CleanHOLDOUT$Credit_Score),
  postResample(predict(RPART,newdata=CleanHOLDOUT),CleanHOLDOUT$Credit_Score) # Highest Accuracy
)

rownames(HOLDOUTresults) <- c('GLM','GLMNET','RPART')

# Results of Holdout testing
HOLDOUTresults

```


**Creating Final Test Data Set**

```{r Creating Final Test Data Set}
Test_Backup <- read.csv("test.csv")
TEST <- Test_Backup

# Lad in data and change data types for predict() function
CleanTEST <- read.csv("Cleaned_TEST.csv")
CleanTEST$Credit_Score <- as.factor(rep(0, nrow(CleanTEST)))
CleanTEST$Credit_Mix <- as.factor(CleanTEST$Credit_Mix)

# predict credit scores with our best model
CleanTEST$Credit_Score <- predict(RPART,newdata=CleanTEST)

# creating new data frame to merge with original holdout to get info on customers

TestCreditScores <- CleanTEST %>% select(ID, Credit_Score)

# writes csv with the CleanTEST data (including predicted credit scores)
# write.csv(CleanTEST, "CleanTEST.csv", row.names = F)


# make sure all IDs are unique before merging data on variable
length(unique(TEST$ID)) == length(unique(TestCreditScores$ID))

# creates data frame with original test data and the new credit predictions
FinalTestData <- merge(TEST, TestCreditScores, by = c("ID" = "ID"))
# write.csv(FinalTestData, "FinalTestData.csv", row.names = F)

```


**Further Data Analysis**

```{r Further Data Analysis}
# Load in final data set with tested values
FinalTestData <- read.csv("FinalTestData.csv")

# Each customer in this new data set is observed 4 times, rather than 8 like the training data
test <- FinalTestData %>% group_by(Customer_ID) %>%  summarise(numObservations = n())
table(test$numObservations)


# We want to look at the final month for each customer to see if their credit is acceptable or not
FinalMonth <- seq(from = 4, to = nrow(FinalTestData), length.out = nrow(FinalTestData)/4)
#subsetting the data to only take the last month of each customer
CustFinalMonth <- FinalTestData[FinalMonth,]


# This value shows us that 71.936% of customers have an acceptable Credit Score rating
mean(CustFinalMonth$Credit_Score == "Acceptable")

# Bar plot of Credit score rating by occupation
ggplot(data = CustFinalMonth, aes(x = Occupation, color = Credit_Score)) + geom_bar() +theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))


# filtered data of all records with Acceptable Credit score rating
Acceptable <- CustFinalMonth %>% filter(Credit_Score == "Acceptable")

# filtered data of all records with Unacceptable Credit score rating
Unacceptable <- CustFinalMonth %>% filter(Credit_Score == "Unacceptable")

# Income metrics 
summary(Acceptable$Annual_Income)
summary(Unacceptable$Annual_Income)

Aincome <- hist(Acceptable$Annual_Income)
Uincome <- hist(Unacceptable$Annual_Income)

A1 <- rgb(255,0,0, max = 255, alpha = 80, names = "lt.red")
U2 <- rgb(0,0,153,max = 255, alpha = 80, names = "lt.blue")


plot(Aincome, col = A1, xlab = "Income", main = "Income by Credit Score");plot(Uincome, add = TRUE, col = U2);legend("topright", c("Acceptable", "Unacceptable"), fill=c("pink", "light blue"))


# Debt metrics and visualizations
summary(Acceptable$Outstanding_Debt)
summary(Unacceptable$Outstanding_Debt)

hA <- hist(Acceptable$Outstanding_Debt)
hU <- hist(Unacceptable$Outstanding_Debt)

A1 <- rgb(255,0,0, max = 255, alpha = 80, names = "lt.red")
U2 <- rgb(0,0,153,max = 255, alpha = 80, names = "lt.blue")


plot(hA, col = A1, xlab = "Outstanding Debt", main = "Credit Score Outstanding Debt");plot(hU, add = TRUE, col = U2);legend("topright", c("Acceptable", "Unacceptable"), fill=c("pink", "light blue"))


# Interest rate visualizations
summary(Acceptable$Interest_Rate)
summary(Unacceptable$Interest_Rate)

(Acceptable$Interest_Rate)

ggplot(data = CustFinalMonth, aes(x = Interest_Rate, color = Credit_Score)) + geom_histogram()

```


