---
title: "BZAN 542 Project"
author: "Group 10"
link: https://www.kaggle.com/datasets/clkmuhammed/creditscoreclassification
---

```{r Load in data and packages}
library(regclass)  
library(rpart)
library(randomForest)
library(gbm)
library(caret)
library(pROC)
library(dplyr)
library(tidyr)
library(ggplot2)

# library(h2o) #automl https://github.com/h2oai/h2o-tutorials/tree/master/h2o-world-2017/automl
# #h2o.automl()


#Training and Holdout data are already defined on Kaggle
# Create training and backup to training data
Train_Backup <- read.csv("train.csv")
DATA <- Train_Backup

# Loading in testing data and creating a backup
Test_Backup <- read.csv("test.csv")
TEST <- Test_Backup

# Splitting Data into Training and Holdout sets
set.seed(542) # set the seed so it is the same TRAIN and HOLDOUT for whoever runs the code
train.rows <- sample(1:nrow(DATA), .7*nrow(DATA))

TRAIN <- DATA[train.rows,]
HOLDOUT <-  DATA[-train.rows,]

```



**Data Exploration**

```{r Data Exploration}
# Data is broken down by customer.
DATA[which(DATA$Customer_ID == 3392),]
# Each customer looks to have 8 months worth of credit data
test <- DATA %>% group_by(Customer_ID) %>%  summarise(numObservations = n())
table(test$numObservations)
# Customers observations will be separated in TRAINING and HOLDOUT because the records are randomly chosen

# The TRAIN dataset has an extra column (Credit_Score). This appears to be the variable that we will be predicting with the HOLDOUT data.
colnames(DATA)[which(colnames(DATA)!=colnames(TEST))]

# Checking for NAs in both datasets
Train_NA <- sapply(TRAIN, function(y) sum(length(which(is.na(y))))) 
data.frame(Train_NA) # No NAs in the TRAINING data

Holdout_NA <- sapply(HOLDOUT, function(y) sum(length(which(is.na(y))))) 
data.frame(Holdout_NA) # No NAs in the HOLDOUT data
```

Some questions to think about:

-What determines if a client qualifies for a credit card loan?

-Does payment behavior correlate with loan acceptance?

-How does bad credit affect loan acceptance?

-How does occupation affect credit scores?


**Data Cleaning**

```{r Data Cleaning}
# We received data for both training and testing. 
# The Training data was split into the HOLDOUT and TRAIN data sets seen here
# The TEST data set also needs to undergo the same cleaning process in order to be used by the model
# We want to limit the amount of columns that use text, to give the model more data to make predictions on


# Setting ID numbers to be factor data type
TRAIN$ID <- as.factor(TRAIN$ID)
TRAIN$Customer_ID <- as.factor(TRAIN$Customer_ID)

HOLDOUT$ID <- as.factor(HOLDOUT$ID)
HOLDOUT$Customer_ID <- as.factor(HOLDOUT$Customer_ID)

TEST$ID <- as.factor(TEST$ID)
TEST$Customer_ID <- as.factor(TEST$Customer_ID)


# Group Good and Standard Credit to be "Acceptable" and leave bad as "Unacceptable"
# table(TRAIN$Credit_Score)
TRAIN$Credit_Score <- as.factor(ifelse(TRAIN$Credit_Score == "Poor", "Unacceptable", "Acceptable"))
HOLDOUT$Credit_Score <- as.factor(ifelse(HOLDOUT$Credit_Score == "Poor", "Unacceptable", "Acceptable"))
# Poor credit score would be acceptable, good or standard would be unacceptable


# Change Credit_Mix ( Bad = 0, Standard = 1, Good = 2 )
TRAIN$Credit_Mix <- as.factor(ifelse(TRAIN$Credit_Mix == "Bad", 0, ifelse(TRAIN$Credit_Mix == "Standard", 1, 2)))
HOLDOUT$Credit_Mix <- as.factor(ifelse(HOLDOUT$Credit_Mix == "Bad", 0, ifelse(HOLDOUT$Credit_Mix == "Standard", 1, 2)))
TEST$Credit_Mix <- as.factor(ifelse(TEST$Credit_Mix == "Bad", 0, ifelse(TEST$Credit_Mix == "Standard", 1, 2)))



# Changing Payment_Behavior from a word to a T/F
TRAIN$High_spent_Large_value_payments <- ifelse(TRAIN$Payment_Behaviour == "High_spent_Large_value_payments", 1, 0)
TRAIN$High_spent_Medium_value_payments <- ifelse(TRAIN$Payment_Behaviour == "High_spent_Medium_value_payments", 1, 0)
TRAIN$High_spent_Small_value_payments <- ifelse(TRAIN$Payment_Behaviour == "High_spent_Small_value_payments", 1, 0)
TRAIN$Low_spent_Large_value_payments <- ifelse(TRAIN$Payment_Behaviour == "Low_spent_Large_value_payments", 1, 0)
TRAIN$Low_spent_Medium_value_payments <- ifelse(TRAIN$Payment_Behaviour == "Low_spent_Medium_value_payments", 1, 0)
TRAIN$Low_spent_Small_value_payments <- ifelse(TRAIN$Payment_Behaviour == "Low_spent_Small_value_payments", 1, 0)
TRAIN$Payment_Behaviour <- NULL

HOLDOUT$High_spent_Large_value_payments <- ifelse(HOLDOUT$Payment_Behaviour == "High_spent_Large_value_payments", 1, 0)
HOLDOUT$High_spent_Medium_value_payments <- ifelse(HOLDOUT$Payment_Behaviour == "High_spent_Medium_value_payments", 1, 0)
HOLDOUT$High_spent_Small_value_payments <- ifelse(HOLDOUT$Payment_Behaviour == "High_spent_Small_value_payments", 1, 0)
HOLDOUT$Low_spent_Large_value_payments <- ifelse(HOLDOUT$Payment_Behaviour == "Low_spent_Large_value_payments", 1, 0)
HOLDOUT$Low_spent_Medium_value_payments <- ifelse(HOLDOUT$Payment_Behaviour == "Low_spent_Medium_value_payments", 1, 0)
HOLDOUT$Low_spent_Small_value_payments <- ifelse(HOLDOUT$Payment_Behaviour == "Low_spent_Small_value_payments", 1, 0)
HOLDOUT$Payment_Behaviour <- NULL

TEST$High_spent_Large_value_payments <- ifelse(TEST$Payment_Behaviour == "High_spent_Large_value_payments", 1, 0)
TEST$High_spent_Medium_value_payments <- ifelse(TEST$Payment_Behaviour == "High_spent_Medium_value_payments", 1, 0)
TEST$High_spent_Small_value_payments <- ifelse(TEST$Payment_Behaviour == "High_spent_Small_value_payments", 1, 0)
TEST$Low_spent_Large_value_payments <- ifelse(TEST$Payment_Behaviour == "Low_spent_Large_value_payments", 1, 0)
TEST$Low_spent_Medium_value_payments <- ifelse(TEST$Payment_Behaviour == "Low_spent_Medium_value_payments", 1, 0)
TEST$Low_spent_Small_value_payments <- ifelse(TEST$Payment_Behaviour == "Low_spent_Small_value_payments", 1, 0)
TEST$Payment_Behaviour <- NULL


# Dropping columns that won't be used in the model
TRAIN$Name <- NULL
TRAIN$Month <- NULL
TRAIN$SSN <- NULL
TRAIN$Occupation <- NULL
TRAIN$Type_of_Loan <- NULL


HOLDOUT$Name <- NULL
HOLDOUT$Month <- NULL
HOLDOUT$SSN <- NULL
HOLDOUT$Occupation <- NULL
HOLDOUT$Type_of_Loan <- NULL

TEST$Name <- NULL
TEST$Month <- NULL
TEST$SSN <- NULL
TEST$Occupation <- NULL
TEST$Type_of_Loan <- NULL


# Figure out what NM is and what to do with it
#TRAIN$Payment_of_Min_Amount <- as.factor(TRAIN$Payment_of_Min_Amount)
TRAIN$Payment_of_Min_Amount <- NULL
HOLDOUT$Payment_of_Min_Amount <- NULL
TEST$Payment_of_Min_Amount <- NULL


# write.csv(TRAIN, "Cleaned_TRAIN.csv", row.names = F)
# write.csv(HOLDOUT, "Cleaned_HOLDOUT.csv", row.names = F)
# write.csv(TEST, "Cleaned_TEST.csv", row.names = F)


```